<?php
/**
 * @author      Zeki Unal <zekiunal@gmail.com>
 * @description
 *
 * @name        default .phtml
 * @version     0.1
 * @created     2015/12/18 13:01
 */
echo $this->doctype();
?>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <?php echo $this->headTitle('Sample Blog ' . $this->translate('News'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Bootstrap Core CSS -->
    <link href="/assets/theme/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/theme/css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/css/custom.css" rel="stylesheet" />

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Sample Blog</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Home</a> </li>
                <?php if (!$this->zfcUserIdentity()): ?>
                    <li><a href="/user/login">Login</a></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->url('account', array('action' => 'index')); ?>">My Profile</a></li>
                    <li><a href="<?php echo $this->url('zfcuser/logout'); ?>">Logout</a></li>
                <?php endif ?>
            </ul>
        </div>
    </div>
</nav>

<header class="intro-header" style="background-image: url('/assets/theme/img/home-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Sample Blog News</h1>
                    <hr class="small">
                    <span class="subheading">The latest news and headlines from Sample Blog. </span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <?php echo $this->content; ?>

        </div>
    </div>
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="https://twitter.com/SampleBlog" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                        </a>
                    </li>
                    <li>
                        <a href="http://www.facebook.com/sample-blog" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/company/sample-blog-" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('news', array('action' => 'rss')); ?>" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
                                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; <?php echo date('Y') ?> by Zeki Unal <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </div>
    </div>
</footer>

<?php echo $this->inlineScript() ?>

<!-- jQuery -->
<script src="/assets/theme/js/jquery.js"></script>
<!--<script src="http://malsup.github.com/jquery.form.js"></script>-->

<!-- Bootstrap Core JavaScript -->
<script src="/assets/theme/js/bootstrap.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="/assets/theme/js/clean-blog.min.js"></script>

<script src="/assets/library/ckeditor/ckeditor.js"></script>

</body>
</html>
