<?php
/**
 * @author      Zeki Unal <zekiunal@gmail.com>
 * @description
 *
 * @name        post .phtml
 * @version     0.1
 * @created     2015/12/20 01:07
 */
?>
<?php
$title = 'Add new post';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php


$form->setAttribute('action', $this->url('account', array('action' => 'post')));
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <div class="form-group">
        <?php echo $this->formHidden($form->get('news_id')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('title')) ?>
        <?php echo $this->FormElement($form->get('title')); ?>
        <?php echo $this->formElementErrors($form->get('title')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('photo')) ?>
        <?php echo $this->FormElement($form->get('photo')); ?>
        <?php echo $this->formElementErrors($form->get('photo')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('highlight')) ?>
        <?php echo $this->FormElement($form->get('highlight')); ?>
        <?php echo $this->formElementErrors($form->get('highlight')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('text')) ?>
        <?php echo $this->FormElement($form->get('text')); ?>
        <?php echo $this->formElementErrors($form->get('text')) ?>
    </div>


    <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

