<?php
/**
 * @author      Zeki Unal <zekiunal@gmail.com>
 * @description
 *
 * @name        read .phtml
 * @version     0.1
 * @created     2015/12/19 17:16
 */
?>


<?php
$title = $news->title;
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<img src="/content/images/upload/750x750/<?= $news->photo ?>" class="image-content"/>
<p><?= ($news->text) ?></p>
<hr/>
<div class="row">
    <div class="col-sm-8">
        <p class="text-left post-meta">Posted by <a href="#"><?= $news->user()->username ?></a>
            on <?= (new DateTime($news->created_at))->format('F d, Y / H:i') ?></p>
    </div>
    <div class="col-sm-4">
        <p class="text-right">
    <span class="fa-stack">
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-file-pdf-o fa-stack-1x fa-inverse"></i>
    </span>

            <a href="<?php echo $this->url('news', array('action' => 'pdf', 'id' => $news->news_id), array('query' => array('download' => 1))); ?>"
               target="_blank">Download </a> or
            <a href="<?php echo $this->url('news', array('action' => 'pdf', 'id' => $news->news_id)); ?>"
               target="_blank">view</a>
        </p>
    </div>
</div>


