<?php
/**
 * @author      Zeki Unal <zekiunal@gmail.com>
 * @description
 *
 * @name        login .phtml
 * @version     0.1
 * @created     2015/12/19 21:47
 */
?>
<?php
/**
 * @var \Zend\Form\Form $form
 */
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
$form->setAttribute('id', 'login-form');
$form->setAttribute('role', 'form');
?>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-login">
            <div class="panel-heading">
                <div class="row">

                    <div class="col-xs-6">
                        <a href="#" class="active" id="login-form-link">Login</a>
                    </div>
                    <?php if ($this->enableRegistration) : ?>
                    <div class="col-xs-6">
                        <a href="/user/register">Register</a>
                    </div>
                    <?php endif; ?>
                </div>
                <hr>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $this->form()->openTag($form) ?>
                        <?php echo $this->formElementErrors($form->get('identity')) ?>
                        <div class="form-group">


                            <?php echo $this->formLabel($form->get('identity')) ?>
                            <?php echo $this->formInput(
                                $form->get('identity')
                                    ->setAttribute('id', 'identity')
                                    ->setAttribute('tabindex', 1)
                                    ->setAttribute('class', 'form-control')
                                    ->setAttribute('placeholder', 'Email')
                                )
                            ?>

                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('credential')) ?>
                            <?php echo $this->formInput(
                                    $form->get('credential')
                                        ->setAttribute('id', 'credential')
                                        ->setAttribute('tabindex', 2)
                                        ->setAttribute('class', 'form-control')
                                        ->setAttribute('placeholder', 'Password')
                                )
                            ?>

                        </div>

                        <?php if ($this->redirect): ?>
                            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>"/>
                        <?php endif ?>
                        <div class="form-group">
                            <div class="row">

                                <div class="col-sm-6">

                                </div>
                                <div class="col-sm-6">
                                    <?php
                                    echo $this->formButton(
                                        $form->get('submit')
                                            ->setAttribute('class', 'form-control btn btn-login')
                                            ->setAttribute('name', 'login-submit')
                                            ->setAttribute('id', 'login-submit')
                                            ->setAttribute('tabindex', 4)
                                        , 'Log In'
                                    )
                                    ?>
                                </div>
                            </div>
                        </div>

                        <?php echo $this->form()->closeTag() ?>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>






