<?php
/**
 * @author      Zeki Unal <zekiunal@gmail.com>
 * @description
 *
 * @name        verify .phtml
 * @version     0.1
 * @created     2015/12/20 16:48
 */
?>
<?php
$title = 'Confirm Account Your Account';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<h4><?= $error ?></h4>

<p>Please try again.</p>

<p><a href="/account/verify"></a></p>

<p><a href="<?php echo $this->url('account', array('action' => 'verify'), array('query' => array('resend' => 1))); ?>">Resend verification link </a></p>


